spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sellcloud_user?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: user
server:
  port: 9092